name: Refreshing the Model with New Data each monday at 00:00

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  run_recommendation_system:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Re Run Recommendation System Script
        run: python model/recommendation-system.py
