name: Unitary test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5' 

      - name: Install dependency
        run: pip install -r requirements.txt 

      - name: Exécution des tests unitaires
        run: pytest
