name: Unitary test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'
          architecture: 'x64'

      - name: Install numpy and cython
        run: |
          pip install numpy cython

      - name: Replace scikit-surprise version
        run: |
          sed -i '/scikit-surprise==1.1.3/d' requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clone surprise repository
        run: git clone https://github.com/NicolasHug/surprise.git

      - name: Install surprise from cloned repository
        run: |
          cd surprise
          python setup.py install

      - name: Run unit tests
        run: pytest api/test_api.py


